# Generated by Django 5.0 on 2023-12-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatrimonyApp', '0002_alter_user_address_alter_user_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
