# Generated by Django 5.0 on 2023-12-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrimonyApp', '0004_person_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='intrests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
