# Generated by Django 5.0 on 2023-12-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrimonyApp', '0006_person_company_person_education_person_jobtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='language',
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='jobtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
