# Generated by Django 5.0 on 2023-12-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrimonyApp', '0007_remove_person_language_alter_person_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
