# Generated by Django 5.0 on 2023-12-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrimonyApp', '0012_chat_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
