# Generated by Django 5.0 on 2024-01-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrimonyApp', '0013_alter_chat_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
    ]
