# Generated by Django 5.1.7 on 2025-04-23 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrimonyApp', '0015_package_membership_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_details', to='MatrimonyApp.package'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_payment', to='MatrimonyApp.membership'),
        ),
    ]
