# Generated by Django 5.1.7 on 2025-04-23 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatrimonyApp', '0016_membership_expiry_date_package_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_days',
        ),
        migrations.AlterField(
            model_name='membership',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membershi_details', to='MatrimonyApp.package'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membershi_details', to='MatrimonyApp.membership'),
        ),
    ]
